export interface SourcingPreview {
    id:string,
    vendor: {
        id: string,
        name: string,
        location: string,
        address: string,
        city: string,
        state: string,
        pin: string,
        country: string,
        office_email1: string,
        office_email2: string,
        office_phone1: string,
        office_phone2: string,
        gst_number: number,
        payment_term: number,
        advance_persentage: number,
        inco_term: string,
        created_at: string,
        updated_at: string,
        created_by: number
    },
    vendor_contact_person: {
        id:string,
        name: string,
        mobileNo1:string,
        mobileNo2: string,
        email1: string,
        email2: string,
        created_at: string,
        updated_at: string,
        supplier_name: string,
        created_by: number
    },
    offer_reference: string,
    offer_date: Date,
    billing_address: string,
    shipping_address: string,
    delivery_date: Date,
    requester: {
        id:string,
        requester: number
    },
    receiver_name:string,
    receiver_phone1:string,
    receiver_phone2: string,
    receiver_dept: string,
    payment_term: number,
    advance_percentage: number,
    freight_charges: number,
    custom_duties:number,
    pf: number,
    insurance: number,
    mode_of_transport:string,
    inco_terms: string,
    installation: string,
    comments: string,
    di1: string,
    di2: string,
    di3: string,
    di4: string,
    di5: string,
    di6: string,
    di7: string,
    di8: string,
    di9: string,
    di10: string,
    vpo_lineitems: any
}

