export interface SupplierCheckInfo {
    id: string,
    vendor:any,
    name: string,
    location: string,
    address: string,
    city: string,
    state: string,
    pin: number,
    country: string,
    office_email1: string,
    office_email2: string,
    office_phone1 : string,
    office_phone2 : string,
    gst_number : number,
    payment_term: number,
    advance_persentage: number,
    inco_term: string,
    created_at: any,
    updated_at: any,
    created_by: number
}
